// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createSafeClient(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('Supabase env vars missing – running in offline mode.');
    // Return a dummy proxy that won't crash when methods are called
    return new Proxy({} as SupabaseClient<Database>, {
      get: (_target, prop) => {
        if (prop === 'auth') {
          return {
            onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
            getSession: () => Promise.resolve({ data: { session: null }, error: null }),
            signOut: () => Promise.resolve({ error: null }),
            signInWithPassword: () => Promise.resolve({ data: {}, error: { message: 'Supabase not configured' } }),
            signUp: () => Promise.resolve({ data: {}, error: { message: 'Supabase not configured' } }),
          };
        }
        if (prop === 'from') {
          return () => ({
            select: () => ({ eq: () => ({ maybeSingle: () => Promise.resolve({ data: null, error: null }) }) }),
            upsert: () => Promise.resolve({ error: { message: 'Supabase not configured' } }),
          });
        }
        if (prop === 'storage') {
          return { from: () => ({ upload: () => Promise.resolve({ error: { message: 'Supabase not configured' } }), getPublicUrl: () => ({ data: { publicUrl: '' } }) }) };
        }
        if (prop === 'functions') {
          return { invoke: () => Promise.resolve({ data: null, error: { message: 'Supabase not configured' } }) };
        }
        return () => {};
      },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export const supabase = createSafeClient();